# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'QuizMaker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuizMaker
  pod 'SwiftyJSON', '~> 4.0'
  pod 'FMDB'
  pod 'RAMAnimatedTabBarController', '~> 3.5.0'
  pod 'SwiftReorder', '~> 3.0'
  pod 'SwipeCellKit', '2.5.0'
  pod 'YNDropDownMenu', '3.0.1'
  pod 'DLRadioButton', '<= 1.4.10'
  pod 'PopupDialog', '0.8.1'
end
